### PR TITLE
Support for subclassing Python objects

### PR DESCRIPTION
**Pull request by philipturner**
I don't have a proper test suite yet. However, I did run through the PyTorch beginner tutorial. PyTorch relies heavily on subclassing and should be a good litmus test. I made this script and it runs successfully on arm64 macOS: [gist](https://gist.github.com/philipturner/d6fe8c9458bc22a1b7417d54e47e5f40). Pay attention to line 61 for an example of how to use subclassing.

This contains commits from the following pull requests. Therefore, there may be conflicts if you merge the following first:
- https://github.com/pvieito/PythonKit/pull/43
- https://github.com/pvieito/PythonKit/pull/44

CC: @liuliu @ephemer

### CODE REVIEW

**Comment by liuliu** [comment]
I am wondering if this can feel more natural (i.e. hide the detail as much as possible) if we do this with `Mirror` and just let you declare a normal class:
```
struct CustomNetwork: PythonClass {
  static var superclass = [torch.nn.Module]
  var __init__ = PythonInstanceMethod { `self`, arguments in
  }
  var forward = PythonInstanceMethod { `self`, arguments in
  }
}

let network = MAGIC_FUNCTION(CustomNetwork.self)(init_arguments)
```

The `MAGIC_FUNCTION` can look like something:
```
  var mirror = Mirror(reflecting: type)
  var name = type.description (??)
  for child in mirror.children {
  }
```

Alternatively, the API can use some kind of builder pattern:
```
let CustomNetwork = PythonClass(name: "CustomNetwork", superclasses: [torch.nn.Module]).defineMethod("__init__", { self, arguments in }).defineMethod("forward", { self, arguments in }).build()
```

Obviously I am out of depth here, but just want to enumerate other design options available for supporting subclasses.

**Comment by philipturner** [comment]
@liuliu I have doubts that Mirror is that powerful, although I did think about it. That would be awesome, so please prove me wrong!

A function builder API sounds cool, but it’s something that will build on what we have now. It could be a second initializer. I’m not going to spend much more time on this, but please put your ideas into action if you have the time.

For defineMethod, properties are also members, as well as initializers. Your last idea is a little too much for PythonKit, which keeps things as simple as possible.

**Comment by philipturner** [comment]
@pvieito I haven't added proper tests for this yet. Should I add them before merging?

**Comment by pvieito** [comment]
@philipturner Yes, please!

**Comment by philipturner** [comment]
I'm thinking of two tests: one for testing the functionality [here](https://www.geeksforgeeks.org/create-classes-dynamically-in-python) and another for subclassing `Exception` in Swift. Any advice on how I should proceed with testing `Exception`?

If it isn't immediately obvious how to test Exception, then I need a third test for actual subclassing. The GeeksForGeeks post doesn't subclass anything besides `Python.object`, and we need a more rigorous validation of inheritance.

**Comment by philipturner** [comment]
I got test #2 figured out. Subclassing a custom class requires a different syntax than `super().__init__(params)`, but that isn't going to be documented. You'll see what I'm talking about when I update my branch, then we can discuss if it's a concern.

**Comment by philipturner** [comment]
@pvieito I'm ready for your review. Please let me know once you've scanned over all of my code so that I don't trigger CI more than once while committing suggestions.

**Pull request merged**
